# Generated by Django 2.2.1 on 2019-08-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190804_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
