# Generated by Django 2.2.1 on 2019-08-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_article_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='project_reports'),
        ),
    ]
