# Generated by Django 2.2.1 on 2019-11-16 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20190814_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='written_on',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Written On'),
        ),
        migrations.AlterField(
            model_name='book',
            name='read_on',
            field=models.DateField(null=True, verbose_name='Date Read On'),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
