# Generated by Django 2.2.1 on 2019-11-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20191116_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='report',
            field=models.URLField(blank=True, null=True),
        ),
    ]
